FROM python:3.12-slim
LABEL maintainer="Subhransu <subhransud525@gmail.com>"

RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 ffmpeg

# Install required system packages
RUN apt-get update && apt-get install -y build-essential pkg-config libmariadb-dev-compat libmariadb-dev && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app
COPY . /app
WORKDIR /app/